spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/code212
    username: root
    password: 'password'
    pool-size: 30

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: eu-central-1
  accessKeyId: AKIAT2TKEXO3UOQMBDBJ
  secretKey: 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
  s3:
    buckets:
      user: code212-user-code
      problem: code212-problems

openai:
  api:
    key: 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
    url:

  model: gpt-3.5-turbo


